export const CALL_ME_CHANGE_NAME = "CALL_ME_CHANGE_NAME:";
export const CALL_ME_CHANGE_PHONE = "CALL_ME_CHANGE_PHONE";
export const SET_PROJECTS = "SET_PROJECTS";
export const CHANGE_FETCHING_STATUS = "CHANGE_FETCHING_STATUS";